services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME:-search_db}
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
